"""Add missing fields to budget_configs, cost_logs, requests

Revision ID: 3fcc3d2671b5
Revises: 9f1c2d3e4a5b
Create Date: 2026-05-05 23:54:58.552728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fcc3d2671b5'
down_revision: Union[str, Sequence[str], None] = '9f1c2d3e4a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('api_keys_key_key'), 'api_keys', type_='unique')
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.drop_column('api_keys', 'owner')
    op.add_column('budget_configs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('budget_configs', 'is_enabled',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="is_enabled::boolean")
    op.alter_column('budget_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('budget_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_budget_configs_api_key_id'), 'budget_configs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_budget_configs_id'), 'budget_configs', ['id'], unique=False)
    op.create_index(op.f('ix_budget_configs_user_id'), 'budget_configs', ['user_id'], unique=False)
    op.drop_constraint(op.f('budget_configs_api_key_id_fkey'), 'budget_configs', type_='foreignkey')
    op.create_foreign_key(None, 'budget_configs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'budget_configs', 'api_keys', ['api_key_id'], ['id'], ondelete='CASCADE')
    op.add_column('cost_logs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('cost_logs', sa.Column('model', sa.String(), nullable=True))
    op.alter_column('cost_logs', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cost_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_cost_logs_api_key_id'), 'cost_logs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_cost_logs_id'), 'cost_logs', ['id'], unique=False)
    op.create_index(op.f('ix_cost_logs_user_id'), 'cost_logs', ['user_id'], unique=False)
    op.drop_constraint(op.f('cost_logs_api_key_id_fkey'), 'cost_logs', type_='foreignkey')
    op.create_foreign_key(None, 'cost_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cost_logs', 'api_keys', ['api_key_id'], ['id'], ondelete='CASCADE')
    op.add_column('requests', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('cost_usd', sa.Float(), nullable=True))
    op.alter_column('requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_requests_api_key_id'), 'requests', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    op.create_index(op.f('ix_requests_user_id'), 'requests', ['user_id'], unique=False)
    op.drop_constraint(op.f('requests_api_key_id_fkey'), 'requests', type_='foreignkey')
    op.create_foreign_key(None, 'requests', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'requests', 'api_keys', ['api_key_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'total_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'total_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('users', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.create_foreign_key(op.f('requests_api_key_id_fkey'), 'requests', 'api_keys', ['api_key_id'], ['id'])
    op.drop_index(op.f('ix_requests_user_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_api_key_id'), table_name='requests')
    op.alter_column('requests', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('requests', 'cost_usd')
    op.drop_column('requests', 'tokens_used')
    op.drop_column('requests', 'user_id')
    op.drop_constraint(None, 'cost_logs', type_='foreignkey')
    op.drop_constraint(None, 'cost_logs', type_='foreignkey')
    op.create_foreign_key(op.f('cost_logs_api_key_id_fkey'), 'cost_logs', 'api_keys', ['api_key_id'], ['id'])
    op.drop_index(op.f('ix_cost_logs_user_id'), table_name='cost_logs')
    op.drop_index(op.f('ix_cost_logs_id'), table_name='cost_logs')
    op.drop_index(op.f('ix_cost_logs_api_key_id'), table_name='cost_logs')
    op.alter_column('cost_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cost_logs', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('cost_logs', 'model')
    op.drop_column('cost_logs', 'user_id')
    op.drop_constraint(None, 'budget_configs', type_='foreignkey')
    op.drop_constraint(None, 'budget_configs', type_='foreignkey')
    op.create_foreign_key(op.f('budget_configs_api_key_id_fkey'), 'budget_configs', 'api_keys', ['api_key_id'], ['id'])
    op.drop_index(op.f('ix_budget_configs_user_id'), table_name='budget_configs')
    op.drop_index(op.f('ix_budget_configs_id'), table_name='budget_configs')
    op.drop_index(op.f('ix_budget_configs_api_key_id'), table_name='budget_configs')
    op.alter_column('budget_configs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('budget_configs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('budget_configs', 'is_enabled',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('budget_configs', 'user_id')
    op.add_column('api_keys', sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.create_unique_constraint(op.f('api_keys_key_key'), 'api_keys', ['key'], postgresql_nulls_not_distinct=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
